-- Create the table for storing enquiries
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  company text,
  event_type text,
  event_theme text,
  preferred_date date,
  budget_range text,
  location text,
  description text,
  services text[], -- Array of strings for services
  status text default 'new' -- To track status (new, contacted, closed, etc.)
);

-- Enable Row Level Security (RLS)
alter table public.enquiries enable row level security;

-- Create a policy to allow the service role (API) to insert data
-- We don't necessarily need a policy for the service role as it bypasses RLS, 
-- but it's good practice if you ever switch to client-side submission (though we are using server-side).

-- If you were inserting from the client (anon key), you would need:
-- create policy "Enable insert for everyone" on public.enquiries for insert with check (true);

-- For now, since we use the Service Role key in the API route, we are good.
-- But if you want to view these in the Supabase Dashboard as an admin user, you might want read access:
create policy "Enable read access for authenticated users only"
on public.enquiries
for select
to authenticated
using (true);
